ORDERS Table
CREATE TABLE ORDERS (
    ORDER_ID NUMBER(5) PRIMARY KEY,
    CUSTOMER_ID NUMBER(5),
    ORDER_DATE DATE NOT NULL,
    TOTAL_AMOUNT NUMBER(10,2) NOT NULL,
    ORDER_STATUS VARCHAR2(30) NOT NULL,

    CONSTRAINT FK_ORDERS_CUSTOMER
        FOREIGN KEY (CUSTOMER_ID)
        REFERENCES CUSTOMER(CUSTOMER_ID)
);
Table created
ORDER_DETAILS Table
CREATE TABLE ORDER_DETAILS (
    ORDER_DETAIL_ID NUMBER(5) PRIMARY KEY,
    ORDER_ID NUMBER(5),
    PRODUCT_ID NUMBER(5),
    QUANTITY NUMBER(5) NOT NULL,

    CONSTRAINT FK_ORDER_DETAILS_ORDER
        FOREIGN KEY (ORDER_ID)
        REFERENCES ORDERS(ORDER_ID),

    CONSTRAINT FK_ORDER_DETAILS_PRODUCT
        FOREIGN KEY (PRODUCT_ID)
        REFERENCES PRODUCT(PRODUCT_ID)
);
Table created
Insert Orders
INSERT INTO ORDERS VALUES
(1001, 1, DATE '2026-09-22', 1198.00, 'Pending');

INSERT INTO ORDERS VALUES
(1002, 2, DATE '2026-09-22', 999.00, 'Packed');

INSERT INTO ORDERS VALUES
(1003, 3, DATE '2026-09-23', 599.00, 'Shipped');

INSERT INTO ORDERS VALUES
(1004, 4, DATE '2026-09-23', 449.00, 'Delivered');

INSERT INTO ORDERS VALUES
(1005, 5, DATE '2026-09-24', 349.00, 'Pending');

COMMIT;
Insert Order Details
INSERT INTO ORDER_DETAILS VALUES
(1, 1001, 101, 2);

INSERT INTO ORDER_DETAILS VALUES
(2, 1001, 102, 1);

INSERT INTO ORDER_DETAILS VALUES
(3, 1002, 112, 1);

INSERT INTO ORDER_DETAILS VALUES
(4, 1003, 113, 1);

INSERT INTO ORDER_DETAILS VALUES
(5, 1004, 114, 1);

COMMIT;
Display Orders
SELECT * FROM ORDERS;
Add New Order
INSERT INTO ORDERS
VALUES (1006, 1, DATE '2026-09-25', 799.00, 'Pending');

COMMIT;
Update Order Status
UPDATE ORDERS
SET ORDER_STATUS = 'Shipped'
WHERE ORDER_ID = 1001;

COMMIT;
SELECT
    O.ORDER_ID,
    O.CUSTOMER_ID,
    O.ORDER_DATE,
    P.PRODUCT_NAME,
    OD.QUANTITY,
    O.TOTAL_AMOUNT,
    O.ORDER_STATUS
FROM ORDERS O
JOIN ORDER_DETAILS OD
    ON O.ORDER_ID = OD.ORDER_ID
JOIN PRODUCT P
    ON OD.PRODUCT_ID = P.PRODUCT_ID
ORDER BY O.ORDER_DATE;