CREATE TABLE PAYMENT (
    PAYMENT_ID NUMBER(5) PRIMARY KEY,
    ORDER_ID NUMBER(5),
    PAYMENT_DATE DATE NOT NULL,
    PAYMENT_MODE VARCHAR2(20) NOT NULL,
    PAYMENT_AMOUNT NUMBER(10,2) NOT NULL,
    PAYMENT_STATUS VARCHAR2(20) NOT NULL,
    CONSTRAINT FK_PAYMENT_ORDER
        FOREIGN KEY (ORDER_ID)
        REFERENCES ORDERS(ORDER_ID)
);
Table created.

INSERT INTO PAYMENT VALUES
(501, 1001, DATE '2026-09-22', 'UPI', 1198.00, 'SUCCESS');
1 row created.
INSERT INTO PAYMENT VALUES
(502, 1002, DATE '2026-09-22', 'CARD', 999.00, 'SUCCESS');
1 row created.
INSERT INTO PAYMENT VALUES
(503, 1003, DATE '2026-09-23', 'CASH', 750.00, 'FAILED');
1 row created.
INSERT INTO PAYMENT VALUES
(504, 1004, DATE '2026-09-23', 'UPI', 1500.00, 'SUCCESS');
1 row created.
INSERT INTO PAYMENT VALUES
(505, 1005, DATE '2026-09-24', 'CARD', 850.00, 'FAILED');
1 row created.
COMMIT;
Commit complete.

SELECT * 
FROM PAYMENT
WHERE PAYMENT_STATUS = 'SUCCESS';

SELECT * 
FROM PAYMENT
WHERE PAYMENT_STATUS = 'FAILED';

UPDATE PAYMENT
SET PAYMENT_STATUS = 'SUCCESS'
WHERE PAYMENT_ID = 505;

SELECT * FROM PAYMENT
WHERE PAYMENT_ID = 505;

SELECT PAYMENT_MODE, COUNT(*) AS TOTAL_TRANSACTIONS
FROM PAYMENT
GROUP BY PAYMENT_MODE;

SELECT PAYMENT_MODE,
       SUM(PAYMENT_AMOUNT) AS TOTAL_AMOUNT_COLLECTED
FROM PAYMENT
WHERE PAYMENT_STATUS = 'SUCCESS'
GROUP BY PAYMENT_MODE;

SELECT 
    P.PAYMENT_ID,
    P.ORDER_ID,
    P.PAYMENT_DATE,
    P.PAYMENT_MODE,
    P.PAYMENT_AMOUNT,
    P.PAYMENT_STATUS,
    O.ORDER_STATUS
FROM PAYMENT P
JOIN ORDERS O
ON P.ORDER_ID = O.ORDER_ID
ORDER BY P.PAYMENT_ID;